name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: BlueOS-community/Deploy-BlueOS-Extension@v1.4.0
    - name: Deploy BlueOS Extension
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
